# Generated by Django 4.1.3 on 2023-01-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="category",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="profiles",
                to="base.productcategory",
            ),
        ),
    ]
