# Generated by Django 4.1.3 on 2023-01-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_remove_profile_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="category",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="profile", to="base.productcategory"
            ),
        ),
    ]
