# Generated by Django 4.1.3 on 2023-01-12 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_profile_category"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="category",),
        migrations.RemoveField(model_name="profile", name="description",),
        migrations.RemoveField(model_name="profile", name="founded",),
        migrations.RemoveField(model_name="profile", name="headquarter",),
        migrations.RemoveField(model_name="profile", name="image",),
        migrations.RemoveField(model_name="profile", name="industry",),
        migrations.RemoveField(model_name="profile", name="website",),
    ]
