# Generated by Django 4.1.3 on 2023-01-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_alter_orderitem_image_alter_profile_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="image",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
