# Generated by Django 4.1.3 on 2023-01-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_alter_orderitem_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="countInStock",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
