# Generated by Django 4.1.3 on 2023-01-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_product_countinstock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True, default="/no-image.jpeg", null=True, upload_to="profile"
            ),
        ),
    ]
